spring.application.name=TestManagementMicroservice

# --- Database (PostgreSQL) ---
spring.datasource.url=jdbc:postgresql://localhost:5432/Test_platform_db
spring.datasource.username=ilyes
spring.datasource.password=mypassword
spring.datasource.driver-class-name=org.postgresql.Driver

# --- JPA / Hibernate ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server port
server.port=8082

discovery.base-url=http://localhost:8000
